name: mena-advisorCI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x]
        # Set N number of parallel jobs you want to run tests on.
        ci_node_total: [1]
        # set N-1 indexes for parallel jobs
        ci_node_index: [0]
        #ci_node_index: [0, 1, 2, 3, 4]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup environment variables
      run: |
        cp sample.env .env

    - name: Run npm install
      run: |
        npm install
      env:
        CI: true

    - name: Setup MYSQL & Run db-migrate
      env:
        DB_PASSWORD: root
        DB_PORT: ${{ job.services.mysql.ports[3306] }} # get randomly assigned published port
      run: |
        sudo apt-get install -y mysql-client libmysqlclient-dev
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -proot -e "SHOW GRANTS FOR 'root'@'localhost'"
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY 'root';"
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -proot -e "CREATE DATABASE db;"
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -proot -e "USE db;"
        node ./node_modules/db-migrate/bin/db-migrate up:all

    - name: Run code check lint
      run: |
        npm run lint

    - name: Run test
      run: |
        npm test

    - name: Run npm build
      run: |
        npm run build --if-present
      env:
        CI: true
